### ISSUE TITLE
asio-sv example does not work with plain HTTP

### ISSUE THREAD

**Issue by nathansalwen** [nghttp2/nghttp2#1058]
I am running on Ubuntu 16.04.  I installed nghttp2 from github and configured with "--enable-asio-lib".  I then went to examples directory and ran "make;asio-sv 127.0.0.1 8084 1".  I then go to firefox (Build identifier: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0) and try to access http://localhost:8084/ and get the error "The connection was reset".  From chrome I get 

This site can’t be reached

127.0.0.1 unexpectedly closed the connection.
ERR_CONNECTION_CLOSED

I have noticed that if I run 
./nghttpx --conf=. "--frontend=127.0.0.1,3000;no-tls"  "--backend=127.0.0.1,4443;;"
and then access http://localhost:3000 it works as long as port 4443 is an HTTP server from another source such as python.  This means that the underlying libraries can support HTTP access and the problem is probably in the asio wrapper.

I have also been unsuccessful in getting the nghttpx program to access HTTPS services on the backend but think this is probably because I am not using the correct command line.

 ./nghttpx --conf=. "--frontend=127.0.0.1,3000;no-tls" "--backend=127.0.0.1,4443;;proto=h2;tls"

Thank you.  I am overall impressed with the quality of the libraries but have only run into issues with recent testing.

**Comment by tatsuhiro-t** [comment]
asio-sv only understands HTTP/2.  And the browsers only use HTTP/2 over TLS, and they refuse to connect to HTTP/2 without TLS.  That's why connection failed.

As for nghttpx, it supports HTTP/1 too, and browsers use HTTP/1 for cleartext connection.

nghttpx should connect to backend server with TLS.  By default, it validates backend server's certificate.  Usually, nghttpx loads CA certificates from system, but if it does not work, or you are using self-signed certificates, you have to specify CA file using --cacert option.
--backend option can include sni option to validate CN, or SAN in server's certificate.
As a last resort, -k option disables all these validations off.

**Comment by nathansalwen** [comment]
Thank you very much!  After continuing to research the issue, I had come to the conclusion that the support of HTTP1 was probably the reason.  I didn't realize that the nghttpx supports HTTP1.

Thank you so much for the hint on certificate options for nghttpx.  I know I should have figured it out myself but was having trouble.  I now have the proxy server up.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.

**Comment by nathansalwen** [comment]
Thanks for what you did.
