### ISSUE TITLE
Using *_set_error_callback to detect non-http2 peer

### ISSUE THREAD

**Issue by jasnell** [nghttp2/nghttp2#1062]
For the Node.js http2 implementation, we the following test case:

```js
'use strict';

const common = require('../common');
if (!common.hasCrypto)
  common.skip('missing crypto');

const http = require('http');
const http2 = require('http2');

const server = http.createServer(common.mustNotCall());

server.listen(0, common.mustCall(() => {
  const client = http2.connect(`http://localhost:${server.address().port}`);

  client.on('error', console.log);
  client.on('socketError', console.log);

  client.on('close', (...args) => {
    server.close();
  });

}));
```

In other words, an http2 client talking to an http1 server. When this happens, we want to be able to report an error to the `client` (e.g. we want `client.on('error')` to receive an appropriate error.

However, currently when nghttp2 is processing the invalid response from the http1 server, the best we get currently is a callback to the `*_set_error_callback` with a message that says, `Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly."

While we can check for this condition fairly easily within the `*_set_error_callback`, doing so requires us to compare the value of the `msg`, which is less than ideal. An alternate solution would be to add a `*_set_error_callback2` variant that would receive a proper numeric error constant that we can key off rather than using the string value.

**Comment by tatsuhiro-t** [comment]
Sounds good.  At the moment, we use this error callback in only 3 places, so it is relatively easy to change.
We have two options to design error_callback2:

1. pass error code + message, just like the existing callback.  This effectively deprecates the existing error_callback.  Of course, we have to keep old one for backward compatibility.
2. just pass error code, and keep it separate from the exiting one.

I think 1 is a bit better because it contains all information we'd want.  For 2, we are in trouble if someone comes up and wants both error code and message.

**Comment by tatsuhiro-t** [comment]
#1063 implements nghttp2_error_callback2.
