### ISSUE TITLE
Request for security distributors list

### ISSUE THREAD

**Issue by mattklein123** [nghttp2/nghttp2#1476]
Hi,

The https://github.com/envoyproxy/envoy maintainers were caught off guard by https://github.com/nghttp2/nghttp2/security/advisories/GHSA-q5wr-xfw9-q7xr (we have treated this as a zero day and are creating our own security release). 

We would kindly request that the nghttp2 project create a security distributors/notification list and process similar to what we have in Envoy: https://github.com/envoyproxy/envoy/blob/master/SECURITY.md#private-distributors-list.

This will allow consumers of nghttp2 to prepare distributions as needed in the face of pre-disclosed security issues.

Thank you your consideration and happy to discuss this in this issue, over email, or in a meeting.

**Comment by tatsuhiro-t** [comment]
Thank you for raising this issue.  Sorry for the inconvenience this time.
I'm thinking about creating an issue to tell that a security release is scheduled 1 week before disclosure with dedicated label set.

**Comment by mattklein123** [comment]
> I'm thinking about creating an issue to tell that a security release is scheduled 1 week before disclosure with dedicated label set.

A few things:
- We would strongly prefer an email list that we can subscribe to. It's much easier to track than an issue. Google groups would work or I would be more than happy to help setup a list through the CNCF groups.io system given the critical nature of the SW.
- I hope you will still consider a distributors/pre-announce list as is done for other critical OSS. The release process for dependent SW and distributions is complex and not having an advance ability to test patches, prepare releases, etc. is a major hindrance.

**Comment by tatsuhiro-t** [comment]
Thank you for the comment.  I'm now considering posting info to distros mailing list.  At the moment, I'd like to avoid creating new mailing list.

**Comment by mattklein123** [comment]
> Thank you for the comment. I'm now considering posting info to distros mailing list. At the moment, I'd like to avoid creating new mailing list.

1. For approved distributors will you provide patches ahead of time?
2. What will the policy be for becoming an approved distributor or dependent project?

**Comment by mattklein123** [comment]
Hi @tatsuhiro-t I wanted to see if there was any update here. I think from the Envoy side we consider this a very important request and would be happy to help out if needed with process or anything else. cc @htuch

**Comment by tatsuhiro-t** [comment]
I have no update about this.  Sorry about that.

**Comment by tatsuhiro-t** [comment]
That means, let me try issue based security notice as described in https://github.com/nghttp2/nghttp2/issues/1476#issuecomment-641396285 and distros@openwall mailing list.  If it does not work very well, then I'll reconsider the process again.

**Comment by mattklein123** [comment]
@tatsuhiro-t it would be great to get the policy written down somewhere? Would Envoy count as a distributor and get pre-notification so that we can prepare our own releases?

**Comment by htuch** [comment]
Yeah, I think what's really important is to be able to avoid zero days at either distributors or large service operators that rely on Envoy. 1 week is unlikely not sufficient, since rollouts can take 2 weeks or more in some orgs, Envoy has standardized the official embargo lead time as 3 weeks.

Envoy borrowed from the k8s policy when we created our [security policy](https://github.com/envoyproxy/envoy/blob/master/SECURITY.md) and we've since spent a lot of time refining it. You might not need something this complex for nghttp2, but arguably the same reasons that many of the items in our sec policy make sense apply to nghttp2 as a core data plane dependency.

We could propose a skeleton security policy in a PR if that helps move this forward.

**Comment by tatsuhiro-t** [comment]
Wrote policy, see 32ac8bdf791eacd874b4d96e5d05c780f12cf646
Refer to https://oss-security.openwall.org/wiki/mailing-lists/distros how to join the distros list.

**Comment by htuch** [comment]
@tatsuhiro-t I don't think Envoy itself or a service operator such as Google qualifies for this distribution list. From our perspective, this is a major blocker and doesn't resolve the Envoy concerns. Also, as mentioned above, 1 week is insufficient lead time.

**Comment by tatsuhiro-t** [comment]
In my opinion, each project has its own liberty to define its own security policy.
If a project has to create a security policy to fulfill all the requirement of all projects which depend on it, it is very hard to achieve it.

**Comment by tatsuhiro-t** [comment]
The defined security policy is a project decision, and we will revisit it if we find that it is absolutely unworkable.

**Comment by jasnell** [comment]
My apologies for jumping into a thread that's been closed. I absolutely agree that some form of early notification would be a good thing, and if there's any way that I can help with that @tatsuhiro-t please let me know! in Node.js, we try to announce a week in advance that a security release is coming but we also do not share any details or patches in advance. In fact we have strict rules about not doing so! That said, it can be difficult.

@tatsuhiro-t, may I ask what your primary concerns are around this, if any? And, how can I help?

**Comment by jasnell** [comment]
btw, @tatsuhiro-t ... +1 on the policy you've described with the one exception that Node.js as a project would not qualify for membership in that distribution list, and therefore couldn't take advantage of it at all. While Node.js can make use of distro provided nghttp2 shared libraries in some of our distributions, we rely primarily on a statically linked version in our supported releases. We don't need details of the vulnerabilities early as much as we just need a heads up that a security release is coming so that we know we will need to put in some work to investigate and update quickly once it it released.
