### ISSUE TITLE
stream user data not cleared?

### ISSUE THREAD

**Issue by icing** [nghttp2/nghttp2#2018]
In curl, we seem to have a rare case where a stream's `user_data` is not cleared completely and the old value is still being passed to `on_stream_close` callback. See https://github.com/curl/curl/issues/10936.

Reading the code in nghttp2_session.c:7785+, it seems to me that the outbound queue is only inspected when the stream was no longer found via `nghttp2_session_get_stream()`. So, if a RST_STREAM outbound item is already there, it would not be cleared. Is that correct?

We have the pattern in curl where we first `nghttp2_submit_rst_stream()` the stream and then call `nghttp2_session_set_stream_user_data(..., NULL)`. Which makes this seem likely to happen???

I think we should reverse that, but I would like to understand where the problem originates from.

**Comment by tatsuhiro-t** [comment]
When a request is submitted via nghttp2_submit_request, it is placed in outbound queue ob_syn.  While at it, a corresponding nghttp2_stream object is not created yet.  nghttp2_session_get_stream_user_data does not work (it returns NULL), meanwhile nghttp2_session_set_stream_user_data works, as the nghttp2_submit_request documentation says:

https://nghttp2.org/documentation/nghttp2_submit_request.html

> [!WARNING]
> This function returns assigned stream ID if it succeeds. But that stream is not created yet. The application must not submit frame to that stream ID before [nghttp2_before_frame_send_callback](https://nghttp2.org/documentation/types.html#c.nghttp2_before_frame_send_callback) is called for this frame. This means [nghttp2_session_get_stream_user_data()](https://nghttp2.org/documentation/nghttp2_session_get_stream_user_data.html#c.nghttp2_session_get_stream_user_data) does not work before the callback. But [nghttp2_session_set_stream_user_data()](https://nghttp2.org/documentation/nghttp2_session_set_stream_user_data.html#c.nghttp2_session_set_stream_user_data) handles this situation specially, and it can set data to a stream during this period.

I think the order of nghttp2_submit_rst_stream and nghttp2_session_set_stream_user_data is irrelevant for this issue.
Curl code calls nghttp2_session_set_stream_user_data(s, id, NULL) only when nghttp2_session_get_stream_user_data returns non-NULL.  But because of the reason stated above, if a request is in outbound ob_syn, nghttp2_session_get_stream_user_data returns NULL, therefore stream user data is not cleared.

**Comment by icing** [comment]
Thanks for the explanation, @tatsuhiro-t . That makes sense in this scenario and we'll change our code to unconditionally clear the stream user data before submitting the final RST now. First tests indicate that this solves the issue for us.
