### ISSUE TITLE
Question- Why the 100 Header Limit?

### ISSUE THREAD

**Issue by dman777** [nghttp2/nghttp2#471]
Just found in documentation that the max is 100 and can be changed with --max-header-fields=<N>. For learning purposes, why the limit? Is there a consequence of going over a 100?

**Comment by dman777** [comment]
Just found in documentation that the max is 100 and can be changed with `--max-header-fields=<N>`. For learning purposes, why the limit? Is there a consequence of going over a 100?

**Comment by tatsuhiro-t** [comment]
The value is from Apache's LimitRequestFields default, which is 100.
But Apache only applies to request header fields from client as the directive name suggests.
I think we should also do this limitation to request only.  Because most of the cases the backend server of nghttpx is "trusted", we can pass all header fields.

**Comment by tatsuhiro-t** [comment]
Fixed in 848f8fbe54ec876351c7ab4da22fdb43ead45c39

**Comment by tatsuhiro-t** [comment]
Closing, since we have fix released.
