### ISSUE TITLE
Why does nghttp2_asio_server is closing the connection after read_timeout ?

### ISSUE THREAD

**Issue by rameshrajagopal** [nghttp2/nghttp2#555]
When I configure read_timeout of say "10 seconds" in the asio_server, after 10 seconds, my nghttp2_asio_client is getting session_error_cb, why is it so ? is this a expected behavior ? Does this mean server closes the connection after read_timeout ?

**Comment by tatsuhiro-t** [comment]
I think it is an expected behaviour.  If there is no incoming data in 10 seconds, server closes the connection.

**Comment by rameshrajagopal** [comment]
@tatsuhiro-t then if I want to have long lived connection b/w my client and server , I should increase the read_timeout or what is the preferred way of doing this ?

**Comment by tatsuhiro-t** [comment]
I'm not sure I fully understand your question, but if you want to keep idle connection open as long as possible, set longer timeout.  Note that if timer is reset if server read packet from client.  So as long as client communicates with server within the timeout, it should not drop connection because of the timer.  If server does not work this way, it would be a bug.

**Comment by tatsuhiro-t** [comment]
Closed since asio library has been removed.
