### ISSUE TITLE
Migration guide for backend-http2-connections-per-worker setting

### ISSUE THREAD

**Issue by gpurrenhage** [nghttp2/nghttp2#582]
Just updated to the latest version and discovered that the backend-http2-connections-per-worker setting is deprecated.

In our prior configuration, this setting was very important to getting reasonable performance.  However the migration guide doesn't mention why this option isn't needed anymore, or how many connections will be used.

Is there a different option that provides the same configurability, or is it something that is handled automatically now, or are we limited to a single connection per backend?

**Comment by tatsuhiro-t** [comment]
backend-http2-connection-per-worker was present because previously the number of backend h2 connection was statically configured, and defaulted to 1.
Now the number of backend h2 connection is increased on demand.  We know the maximum number of concurrent streams per connection.  When we push as many request as the maximum concurrency to the one connection, we create another new connection and distribute load and not delay the processing.  This is done automatically.  So I think in your case, just let nghttpx decide the connection handling is probably enough.  But it would be better to measure the performance with the latest nghttpx.

**Comment by gpurrenhage** [comment]
Thank you, that makes perfect sense.  I'll close the issue, but It may be worth updating the 1.9 migration guide with a short blurb to that effect, for anyone else who was using the setting and may have the same questions.

Keep up the great work, we love nghttp2!

**Comment by tatsuhiro-t** [comment]
We updated the migration guide to mention the reason of this removal (52b455c).  Thank you!
