### ISSUE TITLE
Building nghttp2 library on Windows: clumsy management of ssize_t.

### ISSUE THREAD

**Issue by mtm31415926** [nghttp2/nghttp2#616]
Windows C environment does not offer ssize_t type out of the box. Therefore the nghhtp2 library offers to define it in the compiler flags like:

<pre>CFLAGS = ... -Dssize_t=long ...</pre>

This is a questionable way to go for a number of reasons:
- Definition of the data type in the compilation command complicates use of the library in software development: one should not forget to define ssize_t in the same way, which is pretty inconvenient and not flexible;
- Although ssize_t is not defined out of the box on Windows, it is too well known type name to define it in a specific library: a chance of conflict with other code is high;
- Finally, definition of ssize_t as long does not look correct for 64-bit builds; sizeof(long) is 4 for 64-bit Windows while 8-byte data would be more appropriate. Windows introduces SSIZE_T type though.

Looks like the best solution would be introduction of a kind of nghhtp2_ssize_t type, which would be properly typedef'ed for each platform flavor. As a quick workaround, the following method works:

<ol>
<li>The Windows complication flags (locally for the library build only) are changed to</li>
<pre>CFLAGS = ... -Dssize_t=SSIZE_T ...</pre>
<li>The following code is added to file 'includes/nghttp2/nghttp2.h' (line ~32; after ensuring WIN32 is defined):
<pre>#if defined(WIN32)
#  pragma once
#  include &lt;basetsd.h&gt;
typedef SSIZE_T NGHTTP2_SSIZE_T;
#  if !defined(BUILDING_NGHTTP2)
#    define ssize_t NGHTTP2_SSIZE_T
#  endif
#endif</pre></li>
<li>The following code is added to file 'includes/nghttp2/nghttp2.h' (line ~4965; before the final #endif):
<pre>#if defined(WIN32)
#  if !defined(BUILDING_NGHTTP2)
#    undef ssize_t
#  endif
#endif</pre></li>
</ol>

This does not require massive code changes, defines ssize_t properly and consistently for x86/x64 Windows platforms, and encapsulates ssize_t definition inside the library code offering NGHTTP2_SSIZE_T to one who uses this library in their own code.

**Comment by tatsuhiro-t** [comment]
Thank you for suggestion. It looks good to me.

**Comment by tatsuhiro-t** [comment]
Fix committed via c42296a

**Comment by Jan-E** [comment]
This causes a type redefinition error when building other Windows applications that include nghttp2.h, like curl.lib.

See https://github.com/nghttp2/nghttp2/commit/c42296acf1f7a5ded3e9e76f3e05086bed28d175#commitcomment-17965618

**Comment by Jan-E** [comment]
cURL has solved it like this:
https://github.com/curl/curl/blob/master/lib/config-win32.h#L373

Every application that include both curl/lib/config-win32.h as nghttp2.h will fail:
```

Microsoft (R) Program Maintenance Utility Version 11.00.61030.0
Copyright (C) Microsoft Corporation.  All rights reserved.

configuration name: libcurl-vc11-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi
        cl.exe /O2 /DNDEBUG /MD /DCURL_STATICLIB /I. /I ../lib /I../include /nologo /W3 /EHsc /DWIN32 /FD /c /DBUILDING_LIBCURL /I"../../win64build.vc11o102/include" /DUSE_OPENSSL /I"../../win64build.vc11o102/include/openssl" /DUSE_NGHTTP2 /DHAVE_ZLIB_H /DHAVE_ZLIB /DHAVE_LIBZ /DHAVE_LIBSSH2 /DHAVE_LIBSSH2_H /DLIBSSH2_WIN32 /DLIBSSH2_LIBRARY /DUSE_LIBSSH2 /I../.
./win64build.vc11o102/include/libssh2  /DUSE_WIN32_IDN /DWANT_IDN_PROTOTYPES  /DUSE_IPV6  /DUSE_WINDOWS_SSPI /Fo"..\builds\libcurl-vc11-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi-obj-lib/file.obj"  ..\lib\file.c
file.c
../../win64build.vc11o102/include\nghttp2/nghttp2.h(45) : warning C4005: 'ssize_t' : macro
redefinition
        c:\php-sdk\curl-src\lib\config-win32.h(379) : see previous definition of 'ssize_t'
c:\php-sdk\curl-src\lib\http.h(87) : error C2146: syntax error : missing ')' before identifier 'length'
c:\php-sdk\curl-src\lib\http.h(87) : error C2081: 'ssize_t' : name in formal parameter list illegal
c:\php-sdk\curl-src\lib\http.h(87) : error C2061: syntax error : identifier 'length'
c:\php-sdk\curl-src\lib\http.h(87) : error C2059: syntax error : ';'
c:\php-sdk\curl-src\lib\http.h(87) : error C2059: syntax error : ','
c:\php-sdk\curl-src\lib\http.h(87) : error C2059: syntax error : ')'

```

**Comment by bagder** [comment]
Any suggestion on how we should coordinate this between curl and nghttp2?

**Comment by Jan-E** [comment]
No, not yet. And it is not only curl and nghttp2. mod_http2.so and mod_proxy_http2.so of Apache fail to build as well on the macro redefintion in nghttp2.h. I just checked with Apache 2.4.22, VC11, x86. Before this commit in nghttp2 they were building fine.

**Comment by tatsuhiro-t** [comment]
Thank you for telling us.  I missed the case where application defines ssize_t before including nghttp2.
I have no idea how to deal with this since each application has the liberty to define or typedef ssize_t for their own, so revert the commit for now.

**Comment by tatsuhiro-t** [comment]
c42296acf1f7a5ded3e9e76f3e05086bed28d175 has been reverted.

**Comment by jfolker** [comment]
If I might be so bold as to make a suggestion:

In general, **we should use int32_t, int64_t, uint32_t, and uint64_t and cast to size_t and ssize_t for C library and POSIX library calls** because:

- The size of the aforementioned types is self-descriptive.
- The C standard only defines size_t as "the type used by sizeof", and that it is just large enough to describe the size of any data type defined in legal C code. Windows didn't do anything wrong, and they made long and size_t 4 bytes to keep 32-bit applications from breaking back in the days of the rare and elusive 64-bit Windows XP.
- It naturally follows that ssize_t has the same width as size_t, since POSIX defines ssize_t as "the signed variant of size_t".

For extra emphasis, note that I just said size_t is defined by the C standard, and ssize_t is defined separately by POSIX. This was not a typo, and to pitch in my $0.02 it makes ssize_t a bad idea for code building on a non-POSIX OS.

If no one has any objections I'd be happy to do some code cleanup and submit a pull request. It would be a good first PR for this project anyway to get familiar with the codebase.

P.S. If we were to use ssize_t anyway, it should be a typedef and not a macro for the sake of helpful compiler errors. Note that size_t and ssize_t are defined using typedef on all platforms that have a definition.

**Comment by tatsuhiro-t** [comment]
v1.60.0 introduced nghttp2_ssize API.  One can get rid of ssize_t completely if wanted.
