### ISSUE TITLE
Failed: Network Error - when downloading a file in chrome through nghttpx.

### ISSUE THREAD

**Issue by joeshae** [nghttp2/nghttp2#678]
I'm using squid v3.5.20 as a forward proxy, and nghttpx v1.14.0 as a frontend to provide HTTP/2 proxy.

Everything runs right in the past months until today when I was trying to download any free JPG or HDR sample from http://www.cgskies.com/ ( ONLY ON THIS WEBSITE ), the chrome failed with a network error.

If chrome connects to squid http proxy port ( by SwitchyOmega ) directly without nghttpx, there is no problem at all.

But when chrome connects to nghttpx HTTP/2 proxy port ( by SwitchyOmega ), which backend is squid http proxy port, the download fails. But there are no other problems found until now except this website.

So it's obviously there should be something wrong with nghttpx internal. But I cannot figure it out.

There is no error about this failed downloading in nghttpx errorlog-file.

This is the nghttpx access log about the downloading in nghttpx accesslog-file:

```
11.22.33.44 - - [06/Sep/2016:14:56:47 +0800] "GET http://www.cgskies.com/sample.php?id=117&filetype=jpg&code=edaaca26028afc8fe7a9958977507fd7 HTTP/2" 200 874432 "http://www.cgskies.com/sky.php?sky=117&type=cirrus&hdronly=&sortby=rating&page=1&pagesize=" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2850.0 Safari/537.36"
```

Squid works on default port 3128.
This is my nghttpx configs:

```
daemon=yes
http2-proxy=yes
private-key-file=/usr/etc/certs/foobar_com.key
certificate-file=/usr/etc/certs/foobar_com.crt

frontend=0.0.0.0,443
backend=127.0.0.1,3128

accesslog-file=/var/log/nghttpx/access.log
errorlog-file=/var/log/nghttpx/error.log
```

**Comment by tatsuhiro-t** [comment]
It looks like the server is broken.  Here is the response header it sent:

```
< HTTP/1.1 200 OK
< X-Powered-By: PHP/5.3.23
< Content-type: application/force-download
< Content-Transfer-Encoding: binary
< Content-length: 1042561
< Content-disposition: attachment; filename="(snip)"
< Cache-control: max-age=8640000
< Expires: Thu, 15 Dec 2016 00:00:00 GMT
< Content-Encoding: gzip
< Vary: Accept-Encoding
< Date: Tue, 06 Sep 2016 12:08:43 GMT
< Server: lighttpd/1.4.28
```

The server must send the amount of bytes specified in content-length, but it sent only 870K or so, but it is compressed.  It looks like server still sends the uncompressed size in content-length even though it enabled gzip.

In HTTP/1 world, this kind of bad habit is "accepted", just by closing connection after reading the response.
But in HTTP/2, the amount of bytes received and value in content-length header field must match, otherwise, it is malformed, and subject to the error.  This is the exact situation we have here.

**Comment by joeshae** [comment]
Got it. Thank you tatsuhiro!

**Comment by saurabh1etech** [comment]
How do i resolve this issue? I am facing the same issue.
