### ISSUE TITLE
nghttpx: is there any option to disable SNI totally?

### ISSUE THREAD

**Issue by palxex** [nghttp2/nghttp2#680]
In particular scenario user may want to ensure the domain name cannot be reverse from IP, SNI will leak it. Any suggestion?

**Comment by tatsuhiro-t** [comment]
SNI is sent from client (browser) in clear text during TLS handshake.  To stop "leaking", you have to instruct client that it should not send SNI.

**Comment by palxex** [comment]
@tatsuhiro-t  Thanks for your reply! Sorry for the previous naive question, when asking it I'm not entirely sure where the problem is. 
My actual question is, is it possible to use nghttpx http2-proxy mode, while keeping the proxy functions well - to make client browser able to use the site as a HTTPS proxy - and in the same time, deny other guys who can find the server IP from able to get the domain name? 
For example, assume below is the nghttpx.conf on server side: 
```
frontend=*,443
backend=127.0.0.1,3128 #squid listens here in proxy mode
http2-proxy=yes
private-key-file:...
certificate-file:...
```
In this scenario, on client side, browser  like chrome and firefox can use https://DOMAIN as a http/2 secure proxy. But any router like my ISP that able to observe my connection will also able to get the server IP;  then they can just curl -v https://IP, and they will get a "subject: CN=DOMAIN" to get the DOMAIN - and they'll immediately curl it and find this is a proxy server, which is what I want to hide.
Then I'm trying to let the server pretend its a normal https site with another certificate, since nghttpx support subcert; what I notice is the sni=<> syntax( I thought it was pattern - later I found that's wrong ). But after digging I found that in http2-proxy mode, different backend just round-robin, not like in normal mode, they can point to different ip/port by definite rules. After more digging I found the problem could not be resolved by introducing other tools like sniproxy or haproxy in front of nghttpx also, since nghttpx refuse to listen on other port than 443, and I'm not sure http/2 features will still work since nghttpx is not the final tunnel.
So now my question turns out to, is it possible to make what I desired happening without modifying code? If not so, does nghttpx has plan to support this kind of usage? Seems it will need to add a third mode - http2-proxy with pattern-match based forwarding, and add sni name as kind of pattern.

**Comment by tatsuhiro-t** [comment]
Perhaps, you can use dummy certificate as primary certificate which contains dummy CN (e.g., say localhost or whatever), and specify true certificate in subcert option.
With test setup, someone sends request to nghttpx without domain name (without SNI), it gets dummy certificate.  It does not contain true domain name.

While http2-proxy mode cannot behave like non-proxy, but you can use mruby scripting to send back any content instead of forwarding request to the backend.   Utilizing this feature can make nghttpx behave like a web server.  If you can distinguish the connection you'd want to deny from the normal request, you can write mruby script to return custom content if the some conditions meet.  This is something like access control list implemented in mruby script.  For mruby script, refer to the manual https://nghttp2.org/documentation/nghttpx.1.html#mruby-scripting  Perhaps, you can use SNI value to distinguish correct request or not.

I'm not sure you will drop SNI from client, but if someone can inspect packet, they can also read SNI value, and it reveals domain name.

**Comment by palxex** [comment]
Great! The first suggestion solved my problem perfectly. I'll try the second method for multiplexing the port. Thanks for your reply:)
