### ISSUE TITLE
USR2 should gracefully shutdown old processes

### ISSUE THREAD

**Issue by zdzichu** [nghttp2/nghttp2#804]
I think sending USR2 should also turn old processes into graceful shutdown mode.
Right now, USR2 will cause new processes to be spawned. Old ones sticks around until administrator clean them up with QUIT.
Doing `ipc_send(wp, SHRPX_IPC_GRACEFUL_SHUTDOWN);` in old master after spawning new processes would make the old processes auto clean up after all connections are drained.

Was there a reason to leave old processes after connections have been serviced and new processes were spawned?

**Comment by tatsuhiro-t** [comment]
USR2 handling is designed in that way.  This is because there might be downtime between old process exits and new process is ready to serve requests.  We have no communication between old and new process at the moment to coordinate it.

USR2 is used to upgrade nghttpx binary.  Then QUIT signal should be sent to the old process to gracefully shut down it.

The intention is to just reload configuration, send HUP signal to nghttpx.  This does not kill current master process; only worker processes are restarted gracefully.

**Comment by zdzichu** [comment]
OK. As I understand, the fact that we successfully executed new binary does not imply that the new binary is ready to serve requests. That's fine.

So maybe some internal flag `exit_on_idle`, set after executing new binary? Because when new binary is ready to serve requests, the old binary won't receive any new connections. It could serve already open requests and gracefully exit.
And during the time new binary initialises, old binary will serve the connection, won't be "idle" so won't exit.

I'm looking for a way to reduce amount of work administrator has to do. Sending QUIT signal to old binary seems like something which could be automated (or make unnecessary).

**Comment by tatsuhiro-t** [comment]
> So maybe some internal flag exit_on_idle, set after executing new binary? Because when new binary is ready to serve requests, the old binary won't receive any new connections. It could serve already open requests and gracefully exit.
And during the time new binary initialises, old binary will serve the connection, won't be "idle" so won't exit.

I'm not sure I'm fully understand this, when USR2 is used, and both old and new processes are listening on the same port.  The old process may server request in this state because server port is shared.  Only after it receives QUIT signal, old process stops listening.

> I'm looking for a way to reduce amount of work administrator has to do. Sending QUIT signal to old binary seems like something which could be automated (or make unnecessary).

I agree.  At the moment, and it is a bit hacky.  I use the following script to replace nghttpx binary in my site:

```sh
#!/bin/sh

PID=`cat /var/run/nghttpx.pid`

[ -z "$PID" ] && exit 1

kill -USR2 $PID

while true; do
  NEWPID=`cat /var/run/nghttpx.pid`
  [ "$PID" = "$NEWPID" ] || break
  sleep 0.1
done

kill -QUIT $PID
```

**Comment by tatsuhiro-t** [comment]
https://github.com/nghttp2/nghttp2/tree/nghttpx-usr2-graceful-shutdown-with-signal
This is still a WIP.  With this patch, new process sends SIGQUIT signal to old process when it is ready to serve requests.

**Comment by tatsuhiro-t** [comment]
I made a proper PR for the idea written in previous comment.  See #807.
