### ISSUE TITLE
lib feature request: option to disable keeping closed streams

### ISSUE THREAD

**Issue by mattklein123** [nghttp2/nghttp2#810]
In Envoy, we create a large mesh of http/2 connections. I've noticed that a considerable amount of process memory is actually holding on to closed streams (> 80% of memory in some scenarios). Currently, we don't use priority at all for these connections, so the memory is a waste, but worse, it scales with the number of active connections and not total concurrent streams handled by the server.

I'm honestly quite hazy on the spec and the implementation in this area. I roughly understand that previous streams are kept around up to some concurrency level to help with dependency calculation for the priority tree. So I guess a few questions:

1) If we know we are not using priority at all, could there be a way to disable this functionality to avoid the memory use?
2) If (1) is not possible, is there anything we can do to decrease the memory requirements for the kept streams? (For example, just keep a very small amount of data needed for the calculation).

I'm mostly just trying to understand all of the issues at play here.

Thanks,
Matt

**Comment by tatsuhiro-t** [comment]
I will add option to nghttp2_option to disable retaining closed streams.
Meanwhile, you can change the code so that it does not take this branch (https://github.com/nghttp2/nghttp2/blob/001d45efad9c09aadd1a18f23592633a4bd6751a/lib/nghttp2_session.c#L1189) , and observe how much memory you can save.

**Comment by mattklein123** [comment]
Thanks @tatsuhiro-t I will do a quick check to view the memory savings. If possible, can you briefly explain the implications of not maintaining closed streams? What will the effect be if a remote does set a priority or send a priority frame (even though the server currently ignores all priority information)?

**Comment by tatsuhiro-t** [comment]
If server ignores PRIORITY frame, there is no point to retain closed streams.  The sole purpose of keeping closed streams is maintain priority tree as much as possible so that server can apply client designated priority.

Imagine the case that we have stream A, and B.

* A depends on stream 0 (root)
* B depends on A

Then client opens new stream C, and would like to make C depend on B.
But just before server processes incoming stream C, stream B just closed.

If we maintain closed stream B, then server can make stream C depend on stream B as client suggested.
On the other hand, if we don't retain closed stream B, then B will depend on stream 0(root) with default weight as per spec.  Client might observe the differences (or may be not, it depends).  With or without differences, HTTP/2 protocol should work without prioritization.  Not retaining closed stream doesn't break protocol.  Client may get streams in the order it just not expected. 

The relevant part of RFC 7540 is https://tools.ietf.org/html/rfc7540#section-5.3.4

>    It is possible for a stream to become closed while prioritization
   information that creates a dependency on that stream is in transit.
   If a stream identified in a dependency has no associated priority
   information, then the dependent stream is instead assigned a default
   priority (Section 5.3.5).  This potentially creates suboptimal
   prioritization, since the stream could be given a priority that is
   different from what is intended.

>   To avoid these problems, an endpoint SHOULD retain stream
   prioritization state for a period after streams become closed.  The
   longer state is retained, the lower the chance that streams are
   assigned incorrect or default priority values.

>   The retention of priority information for streams that are not
   counted toward the limit set by SETTINGS_MAX_CONCURRENT_STREAMS could
   create a large state burden for an endpoint.  Therefore, the amount
   of prioritization state that is retained MAY be limited.

>   The amount of additional state an endpoint maintains for
   prioritization could be dependent on load; under high load,
   prioritization state can be discarded to limit resource commitments.
   In extreme cases, an endpoint could even discard prioritization state
   for active or reserved streams.  If a limit is applied, endpoints
   SHOULD maintain state for at least as many streams as allowed by
   their setting for SETTINGS_MAX_CONCURRENT_STREAMS.  Implementations
   SHOULD also attempt to retain state for streams that are in active
   use in the priority tree.

**Comment by mattklein123** [comment]
OK thanks for the explanation. I will read the spec more to better understand this. In the near term though, assuming everything continues to work correctly, disabling keeping closed streams seems like a great option for our use case. Thanks for adding the option. Will pick this up when you release.
