### ISSUE TITLE
nghttpx forward proxy mode rewriting queries

### ISSUE THREAD

**Issue by bemasc** [nghttp2/nghttp2#815]
I'd like to use nghttpx as an HTTP/2 frontend to an Apache server with mod_proxy.  My Apache server is both a web server and a proxy server: locations starting with "/" are served locally; locations starting with "http://" are proxied.  (This is Apache + mod_proxy's default behavior.)

I can't figure out how to get nghttpx to act as a frontend to this server.  With `http2-proxy=no`, proxying doesn't work.  With `http2-proxy=yes`, nghttpx seems to rewrite local resource queries into proxy queries, prepending the name from :authority.  This seems like a bug: the docs say "location header field will not be altered" when `http2-proxy=yes`.

Is this a bug?

**Comment by tatsuhiro-t** [comment]
nghttpx does not support this kind of functionality.
If I understand it correctly, the following HTTP/1.1 request is served by apache:

```
GET / HTTP/1.1
...
```

And the following HTTP/1.1 request is proxied to another server:

```
GET http://example.com/ HTTP/1.1
...
```

This works in HTTP/1.1 because most of the browsers always send first form (origin form) to request origin server, while the second form (absolute form) is used if forward proxy is configured.

The workaround is run 2 nghttpx instances. One for reverse proxy to apache with http2-proxy=no, and another one for forward proxy with http2-proxy=yes.

As for location header field, I guess that you probably refer to request URI.  The nghttpx documentation refers to "Location" header field which appears in the HTTP response header commonly with 3xx status code.

**Comment by bemasc** [comment]
Ah, I didn't know that HTTP/2 lacked the origin/absolute form distinction.  Good to know!
