### ISSUE TITLE
Stream prioritization

### ISSUE THREAD

**Issue by haidang12** [nghttp2/nghttp2#879]
I use nghttp2 to do a simple experiment on the stream prioritization. I simultaneously send 2 requests. The weight of 1st request is 72 and 2nd request is 12. And server sends 2 PUSH_PROMISE frames: stream 2 for 1st request and 4 for 2nd request. In my opinion, the server will consecutively send 6 DATA frames of stream 2 and then sends a DATA frame of stream 4. But the reality is not so. You can see below: 

> [  1.081] recv DATA frame <length=16384, flags=0x00, stream_id=2>
[  1.125] recv DATA frame <length=16384, flags=0x00, stream_id=4>
[  1.125] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
	(window_size_increment=32768)
[  1.173] recv DATA frame <length=16384, flags=0x00, stream_id=2>
[  1.173] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=2>
	(window_size_increment=32768)
[  1.217] recv DATA frame <length=16383, flags=0x00, stream_id=2>
[  1.217] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
         (window_size_increment=32767)
[  1.265] recv DATA frame <length=16384, flags=0x00, stream_id=2>
[  1.265] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=2>
        (window_size_increment=32767)
[  1.309] recv DATA frame <length=16384, flags=0x00, stream_id=4>
[  1.309] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
         (window_size_increment=32768)

Server sends only three DATA frames of stream 2 before sending a DATA frame of stream 4. As I know, that's because server see window size of stream 2 is 0. But, I set rtt only 10ms. So I think, prior to deciding to send DATA frame of stream 4, server received WINDOW_UPDATE frame of stream 2. Could you explain this for me? Thank you so much
I apologize if my question has some grammar mistakes. My English is not good

**Comment by tatsuhiro-t** [comment]
It is probably because server performs its job before reading WINDOW_UPDATE.  No matter how small the RTT is, there is still a race between when server reads the socket, and when server process the request based on the input which server already had.

One way to remedy this situation is limit the number of bytes server writes to TCP socket at a time.
https://www.slideshare.net/kazuho/programming-tcp-for-responsiveness show the theory behind this.
nghttpx has that feature implemented with --frontend-http2-optimize-write-buffer-size.

BTW, your English is clear, and easy to read.

**Comment by haidang12** [comment]
Thank you for your answer!. And I have one more question. I think that both priority and flow control feature can be used for the purpose of bandwidth control of each stream. Is that right? Which feature I should use for that purpose?

**Comment by tatsuhiro-t** [comment]
If my understanding is correct, the connection-level flow control limits the overall in-flight data receiver can accept.  Server chooses the value based on the availability of buffer size.
Streams share that overall bandwidth according to the ratio calculated based on the priority.
Stream-level flow control is used to prevent one stream from dominating whole connection, and it just adds extra knob for the protocol.

As RFC 7540 says, if there is no buffer size concern, you can use large flow control window.  The main stream browser uses large (~250MiB) connection flow control window to fully utilize wire bandwidth.  The stream window size could be much smaller though.

**Comment by haidang12** [comment]
How to i set priority for each push stream of a request?

**Comment by tatsuhiro-t** [comment]
You will see the pushed stream in nghttp2_on_frame_recv callback.  Then, use nghttp2_submit_priority to re-prioritize the stream.

**Comment by haidang12** [comment]
I send 2 requests simultaneously. Request 1 depends on stream 11 with exclusive = 0 and request 2 depends on stream 11 with exclusive =1. I think request 1 will depend on request 2. But I see some DATA frames of request 1 interleaved before request 2 got finished. Why does this happen? 

> [  0.396] recv DATA frame <length=16384, flags=0x00, stream_id=4>
[  0.468] recv DATA frame <length=16384, flags=0x00, stream_id=4>
[  0.468] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
          (window_size_increment=32768)
[  0.516] recv DATA frame <length=16384, flags=0x00, stream_id=4>
[  0.560] recv DATA frame <length=16383, flags=0x00, stream_id=4>
[  0.560] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
          (window_size_increment=32767)
[  0.640] recv DATA frame <length=16384, flags=0x00, stream_id=4>
[  0.680] recv DATA frame <length=16384, flags=0x00, stream_id=4>
[  0.680] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
          (window_size_increment=32768)
[  0.728] recv DATA frame <length=16384, flags=0x00, stream_id=2>
[  0.800] recv DATA frame <length=16383, flags=0x00, stream_id=4>
[  0.800] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
          (window_size_increment=32767)
[  0.848] recv DATA frame <length=16384, flags=0x00, stream_id=4>
[  0.868] recv DATA frame <length=7279, flags=0x00, stream_id=4>
[  0.868] recv DATA frame <length=0, flags=0x01, stream_id=4>
          ; END_STREAM

Stream 2 is pushed stream of request 1 and stream 4 is pushed stream of request 2.  And I set w = 30.

**Comment by tatsuhiro-t** [comment]
I'm a bit confused because first you argue about request 1 and 2, and then the pasted log shows pushed streams, and then you wrote about those pushed streams.
Are you interested in pushed stream 2 and 4 or client-initiated stream 1 and 2?

**Comment by haidang12** [comment]
I'm interested in pushed stream. I send 2 requests and server push some pushed streams of each request. And I think these pushed streams will follow the priority information in their request header

**Comment by tatsuhiro-t** [comment]
Thank you for clarification.  I think that interleaving stream 2 and 4 is correct behavior.

The dependency tree is like this after you've set dependencies:

```
11
|
15
|  \
13  4
|
2
```

The stream 13 depends on the stream 11.
Then stream 15 depends on the stream 11 with exclusive bit on, which makes the stream 13 depend on the stream 15.
Then the sever initiates the push stream 2 which is associated the stream 13.
It also initiates the push stream 4 which is associated the stream 15.

According to the HTTP/2 specification, the stream 2 and 4 has no direct dependency between them. Suppose that the server has no data to send in stream 13 and 15.
In that case, the resources which would have been allocated to the stream 15 is distributed among the stream 13 and the stream 4 in proportional to their weight.
Since the stream 13 has no data to send, its resource is transferred to the stream 2.
As a result, the resource allocated to the stream 15 is distributed to stream 2 and 4, and its ratio is the weight of the stream 13 and the stream 4.

**Comment by haidang12** [comment]
I totally understand. Thank you so much!

**Comment by tatsuhiro-t** [comment]
Good to hear that.  Let's close the issue.
