### ISSUE TITLE
Can't update window size

### ISSUE THREAD

**Issue by MisterduncanPr** [nghttp2/nghttp2#890]
I want to set window size (like 2^10 - 1) for a specific ` stream_id = 8 `. I changed nghttp.cc file like this:
`if (config.connection_window_bits != -1) { `                                                                                                   

` int32_t window_size = (1 << config.connection_window_bits) - 1; `
   ` if (rv != 0) { `
    `             return -1; `
   ` } `
 ` } `
 ` else{ `
  `	int32_t window_size = (1 << 10) - 1; `
   ` rv = nghttp2_session_set_local_window_size(session, NGHTTP2_FLAG_NONE, 8,
                                               window_size); `
 `   if (rv != 0) { `
   `    return -1; `
  `  } `
`  }`
However, it was not like I expected that DATA frame has length = 2^10 - 1. The value of length still was default value. Am I missing anything? How can I fix it?

**Comment by tatsuhiro-t** [comment]
First, I'd like to make sure that nghttp2_session_set_local_window_size sets the receiver's window size on local endpoint.  This affects how many bytes the remote endpoint can send without waiting for another window updates.

nghttp2_session_set_local_window_size sets 2^10-1.  But depending on the situation, the remote endpoint has still see larger window size.  For example, by default, the remote endpoint has 64KiB window size.  The individual window size only decreases by sending DATA frames.  The receiver can increase window size, but it cannot decrease it (the receiver can actually decrease window size by sending SETTINGS frame, but it affects all streams).
So what nghttp2_session_set_local_window_size does is that it stops sending WINDOW_UPDATE frame so that the window size becomes the given size, 2^10-1, in this case.
To see this in action, try to send more than 64KiB data from the remote endpoint, 80KiB would be fine.
In order to make it simple, set connection window size to large size, say 16MiB (-W24).

**Comment by MisterduncanPr** [comment]
Actually, I requested 141KiB data from server and the DATA frame had the default value (I did not use -w or -W). Can I set the window size for specific ` stream_id ` in order to get expected DATA frame length for that ` stream_id `? For example, ` stream_id = 8 ` has DATA frame length = 2^8 - 1 but ` stream_id = 10 ` has DATA frame length = 2^13 - 1. Thank you

**Comment by tatsuhiro-t** [comment]
I guess you probably call nghttp2_session_set_local_window_size before stream is created.
Try calling it in before_frame_send_callback or on_frame_send_callback.

**Comment by MisterduncanPr** [comment]
Thank you! It works
