### ISSUE TITLE
h2load: maximum clients 1017?

### ISSUE THREAD

**Issue by outhud** [nghttp2/nghttp2#932]
I've been trying to use h2load with a client size of 2000:

h2load -c2000 -n2000 --threads=4 https://google.com

But it seems I always get only 1017 working (for any client size above 1017):

> requests: 2000 total, 1017 started, 1017 done, 0 succeeded, 2000 failed, 983 errored, 0 timeout
> status codes: 0 2xx, 0 3xx, 1017 4xx, 0 5xx

For each of the errored connections, I see "client could not connect to host" printed to the terminal. I've tried this on two machines (both running Linux Mint 18.1) nghttp2/1.23.0-DEV

Is there a way I can run larger concurrency tests?

**Comment by tatsuhiro-t** [comment]
The maximum number of file descriptor per a single process is limited by OS.
`ulimit -n` will tell you how much file descriptor can be opened per process.  It is typically 1024 by default.
Searching google will tell you how to enlarge this limit.
For example, you have to edit /etc/security/limits.conf, and add following section:
```
* soft nofile 65536
* hard nofile 65536
```
This will raise the maximum number of file descriptor to 65536.
If you are performing load testing, there are other OS parameters which make request/connection fail because of resource exhaustion.
As far as I know, at least the following parameters should be modified:

* /proc/sys/net/ipv4/ip_local_port_range
* /proc/sys/net/ipv4/tcp_tw_reuse
* /proc/sys/net/core/somaxconn

**Comment by tatsuhiro-t** [comment]
And, just in case, don't run h2load against google.com.

**Comment by outhud** [comment]
Thanks. Simply increasing the limit with `ulimit -n 16384` seems to have helped. I'll modify the other parameters also.
