### ISSUE TITLE
How to make nghttp2 use new tunnel after reload config

### ISSUE THREAD

**Issue by humiaozuzu** [nghttp2/nghttp2#989]
Hi, I'm using nghttp2 as an local proxy client like this:

```
browser -> local nghttp2 proxy client -> remote nghttp2 proxy server
```
and with config for local proxy client.

```
backend={ServerAddress},{ServerPort};;proto=h2;tls
frontend=127.0.0.1,6789;no-tls
workers=2
http2-proxy=yes
npn-list=h2
tls-proto-list=TLSv1.2
```
the problem I met was when I visit some website and then change local client config backend to another one and reload nghttp2 proxy client. When visit new website the traffic will go through new server but if I visit the same website as I visit before reloading nghttp2 client will still go through the old server. So is there anyway to let the website go throughout new server?

**Comment by tatsuhiro-t** [comment]
There are 2 ways to achieve this but they might not be elegant:

1.  restart nghttpx instead of reloading configuration
2.  restart browser

**Comment by humiaozuzu** [comment]
But I think for the same site after reloading the program need to use the new tunnel for servers with continuous requests maybe it will never use the new tunnel which makes live reloading meaningless

**Comment by tatsuhiro-t** [comment]
It is not entirely useless.  The new connection uses new configuration, and the old unfinished connections are kept alive.  The old connection eventually closed with idle timeout unless someone or something tries to send data all the time, which is a bit unusual for browser use.  The issue here is you want to new connection immediately, which is the case where we have to use workaround I mentioned above.

**Comment by humiaozuzu** [comment]
@tatsuhiro-t Is there a way to send signal to nghttpx to let it restart? (I know how to send signal to let it reload current config)

**Comment by tatsuhiro-t** [comment]
Perhaps you can kill the old worker process by sending SIGTERM.  I haven't tested it yet.
